生成したトークンを使う前にもう一度チェック

diff --git a/.github/workflows/reusable-release.yml b/.github/workflows/reusable-release.yml
--- a/.github/workflows/reusable-release.yml
+++ b/.github/workflows/reusable-release.yml
@@ -155,6 +155,17 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ github.token }}
 
+      - name: Verify token
+        env:
+          TOKEN: ${{ needs.prepare.outputs.token }}
+        run: |
+          if [[ "${TOKEN}" != "" ]]; then
+            wc -c <<<"${TOKEN}"
+          else
+            echo "::error title=Not generated token::token is empty"
+            exit 1
+          fi
+
       - name: Run GoReleaser
         id: goreleaser
         uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
